version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add Docker Host
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo $DOCKERHOST
            echo 127.0.0.1 oscommerce-test.docker | sudo tee -a /etc/hosts
      - run:
          name: Composer Install
          command: |
            sudo apt install -y python-software-properties
            sudo add-apt-repository -y ppa:ondrej/php
            find /etc/apt/sources.list.d -type f -name '*.list' -exec sudo apt-get update -o Dir::Etc::sourcelist="{}" ';'
            sudo apt install -y php7.2-fpm php7.2-gd php7.2-curl php7.2-mysql php7.2-dev php7.2-cli php7.2-common php7.2-mbstring php7.2-intl php7.2-zip php7.2-bcmath php7.2-dom node
            curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install
      - run:
          name: Docker compose UP
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose up -d oscommerce-test
            docker-compose up -d selenium
            sleep 15
      - run:
          name: Composer install --no-dev
          command: |
            composer install --no-dev
      - run:
          name: Docker CP the module folders
          command: |
            docker cp ./catalog/ext/. oscommerce-test:/var/www/html/ext/
            docker cp ./catalog/includes/. oscommerce-test:/var/www/html/includes/
      - run:
          name: Composer install
          command: |
            composer install
      - run:
          name: oscommerce-basic
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            catalog/ext/modules/payment/pagantis/vendor/bin/phpunit --group oscommerce-basic
      - run:
          name: oscommerce-configure
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            catalog/ext/modules/payment/pagantis/vendor/bin/phpunit --group oscommerce-configure
  pushRelease:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Package Generation
          command: |
            ./node_modules/.bin/grunt
            mv pagantis.zip pagantis-$CIRCLE_TAG.zip
            ls *.zip
      - run:
          name: Install GitHub CLI
          command: |
            curl -LO https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
            tar xfv linux-amd64-github-release.tar.bz2
            rm linux-amd64-github-release.tar.bz2
            sudo mv bin/linux/amd64/github-release /usr/local/bin/github-release
            sudo chmod +x /usr/local/bin/github-release
      - run:
          name: Push ZIP to GitHub
          command: |
            github-release upload \
                --user pagamastarde \
                --repo oscommerce \
                --tag $CIRCLE_TAG \
                --name pagantis-$CIRCLE_TAG.zip \
                --file pagantis-$CIRCLE_TAG.zip
workflows:
  version: 2
  test-build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  release:
    jobs:
      - pushRelease:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
